name: Update README ‚≠ê 2024
on: workflow_dispatch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: k2bd/advent-readme-stars@v1.0.3
        with:
          userId: 1164527
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: <!--- advent_readme_stars table 2024 --->
          year: 2024
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update stars
